import { Lesson } from '../interfaces'

export default [
  {
    day: 'Пн',
    time: '10:00',
    duration: 120,
    title: 'Аштанга-йога (майсор-класс)',
    level: 'Сложный',
    master: 'Ирина',
  },
  {
    day: 'Пн',
    time: '12:15',
    duration: 90,
    title: 'Хатха-йога для начинающих',
    level: 'Лёгкий',
    master: 'Аниса',
  },
  {
    day: 'Пн',
    time: '16:15',
    duration: 90,
    title: 'Джит Кун-До детская группа',
    level: '5-14 лет',
    master: 'Сергей',
  },
  {
    day: 'Пн',
    time: '18:00',
    duration: 120,
    title: 'Аштанга-йога для начинающих',
    level: 'Средний',
    master: 'Ирина',
  },
  {
    day: 'Пн',
    time: '20:15',
    duration: 90,
    title: 'Хатха-йога для начинающих',
    level: 'Лёгкий',
    master: 'Наталья К.',
  },
  {
    day: 'Вт',
    time: '09:30',
    duration: 90,
    title: 'Хатха-йога для начинающих',
    level: 'Лёгкий',
    master: 'Надежда',
  },
  {
    day: 'Вт',
    time: '11:00',
    duration: 90,
    title: 'Йога для беременных',
    level: 'Лёгкий',
    master: 'Надежда',
  },
  {
    day: 'Вт',
    time: '11:00',
    duration: 90,
    title: 'Йогатерапия',
    level: 'Лёгкий',
    master: 'Аниса',
    note: 'по предварительной записи',
  },
  {
    day: 'Вт',
    time: '19:30',
    duration: 90,
    title: 'Хатха-йога',
    level: 'Средний',
    master: 'Нина',
  },
  {
    day: 'Ср',
    time: '18:00',
    duration: 150,
    title: 'Аштанга-йога (майсор-класс)',
    level: 'Сложный',
    master: 'Ирина',
  },
  {
    day: 'Ср',
    time: '20:15',
    duration: 90,
    title: 'Хатха-йога',
    level: 'Лёгкий',
    master: 'Евгения',
  },
  {
    day: 'Чт',
    time: '10:00',
    duration: 120,
    title: 'Аштанга-йога (майсор-класс)',
    level: 'Сложный',
    master: 'Ирина',
  },
  {
    day: 'Чт',
    time: '12:15',
    duration: 90,
    title: 'Хатха-йога для начинающих',
    level: 'Лёгкий',
    master: 'Аниса',
  },
  {
    day: 'Чт',
    time: '19:30',
    duration: 90,
    title: 'Хатха-йога',
    level: 'Средний',
    master: 'Нина',
  },
  {
    day: 'Пт',
    time: '09:30',
    duration: 90,
    title: 'Хатха-йога для начинающих',
    level: 'Лёгкий',
    master: 'Надежда',
  },
  {
    day: 'Пт',
    time: '11:00',
    duration: 90,
    title: 'Йога для беременных',
    level: 'Лёгкий',
    master: 'Надежда',
  },
  {
    day: 'Пт',
    time: '16:15',
    duration: 90,
    title: 'Джит Кун-До детская группа',
    level: '5-14 лет',
    master: 'Сергей',
    
  },
  {
    day: 'Пт',
    time: '18:00',
    duration: 150,
    title: 'Аштанга-йога (майсор-класс)',
    level: 'Сложный',
    master: 'Ирина',
  },
  {
    day: 'Пт',
    time: '18:30',
    duration: 90,
    title: 'Йогатерапия',
    level: 'Лёгкий',
    master: 'Аниса',
    note: '5, 12 апреля отмена',
  },
  {
    day: 'Пт',
    time: '20:15',
    duration: 90,
    title: 'Хатха-йога для начинающих',
    level: 'Лёгкий',
    master: 'Наталья К.',
  },
  {
    day: 'Сб',
    time: '09:00',
    duration: 90,
    title: 'Общая физическая подготовка',
    level: 'Любой',
    master: 'Сергей',
  },
  {
    day: 'Сб',
    time: '10:45',
    duration: 90,
    title: 'Кундалини-йога',
    level: 'Любой',
    master: 'Татьяна',
  },
  {
    day: 'Сб',
    time: '12:30',
    duration: 90,
    title: 'Хатха-йога',
    level: 'Лёгкий',
    master: 'Евгения',
    note:'6 апреля замена Надежда',
  },
  {
    day: 'Сб',
    time: '14:15',
    duration: 90,
    title: 'Здоровая спина (йога-терапия)',
    level: 'Лёгкий',
    master: 'Евгения',
    note:'6 апреля замена Надежда',
  },
  {
    day: 'Вс',
    time: '17:15',
    duration: 90,
    title: 'Три-йога',
    level: 'Лёгкий',
    master: 'Наталья П.',
  },
  {
    day: 'Вс',
    time: '19:00',
    duration: 90,
    title: 'Хатха-йога для начинающих',
    level: 'Лёгкий',
    master: 'Надежда',
  }
].map(({ day, time, ...i }) => {
  const [ h, m ] = time.split(':').map(Number)
  const weekday = [ 'Пн', 'Вт', 'Ср', 'Чт', 'Пт', 'Сб', 'Вс' ].indexOf(day)
  return {
    ...i,
    id: JSON.stringify({ day, time, ...i }),
    time: h * 60 + m,
    day: weekday,
  }
}) as Lesson[]
